"""initial

Revision ID: 40bf4d945413
Revises: 
Create Date: 2026-05-25 23:10:13.055366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bf4d945413'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_steps', sa.Column('action_type', sa.String(length=20), nullable=True))
    op.add_column('approval_steps', sa.Column('reassigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'approval_steps', 'users', ['reassigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approval_steps', type_='foreignkey')
    op.drop_column('approval_steps', 'reassigned_to')
    op.drop_column('approval_steps', 'action_type')
    # ### end Alembic commands ###
